### ISSUE TITLE
Have logging functions return *logrus.Entry 's

### ISSUE THREAD

**Issue by wrouesnel** [prometheus/log#5]
The normal logrus functions return Entry objects which allow the use of syntax like:
`log.WithField("somefield", "somevalue").Debug("message")`

Since it's one of the big advantages of logrus, it'd be good if it was supported.

**Comment by juliusv** [comment]
Sounds good to me in principle - we don't need it right now, but might want it at some point. Feel free to send a PR if you need it more urgently.

**Comment by fabxc** [comment]
I've not seen the issue back then but see plenty of use cases for ourselves where we have no idea from which of thousands of sub-proccesses a log entry comes from.

@wrouesnel c.f. #6 for a solution
