### ISSUE TITLE
Deprecate this repository

### ISSUE THREAD

**Issue by fabxc** [prometheus/log#6]
A while I ago I've already been arguing for structured logging. For Alertmanager I will apply it from the beginning and hence moved this log package into [common/log](https://godoc.org/github.com/prometheus/common/log) with the following changes.
- Extension by structured logging functionality
- The `*ln` functions were removed as they were equivalent to the plain functions
- Panic level was removed as we do not use it and probably never will
- `Print*` functions as duplicate of `Info*` functions were removed

This package is a wrapper around an existing logging library to make it fit our purpose. We have no intention of being the maintainer of a globally used logging library. Functionality is too limited and specific for this anyway.

The common repo was created exactly for those kind of packages.
The repo should certainly stick around for a while to not break dependencies (c.f. removal of client_golang packages that broke kubernetes builds). However, new projects should use `common/log` and existing ones should be migrated as time allows.

/cc @juliusv @matthiasr @grobie I recall talking to the three of you regarding structured logging and recall you had opinions. The proposed solution is basically a middle ground of structure but also human-readbale messages.

**Comment by juliusv** [comment]
:+1: to everything, except maybe keep the `*ln` variants. Like `fmt.Println` and `fmt.Print`, the former inserts spaces between arguments, the latter doesn't. Sometimes handy.

**Comment by fabxc** [comment]
That's the theoretical behavior. My tests have shown that both insert the spacing.

**Comment by juliusv** [comment]
Hmm, I actually tested it before writing my comment, and they do space as I wrote above for me.

**Comment by fabxc** [comment]
Okay they both seem to space between numbers but behave differently between strings – strange behavior.
I would just indirect `Info` to `Infoln` under the hood then because you never want the non-spaced version anyway – but not feeling strongly.

**Comment by matthiasr** [comment]
I agree that this should not be its own repo. No opinion on which methods are needed or not

**Comment by juliusv** [comment]
Yup, that's analogous to `fmt.Print` and `fmt.Println` behavior too. Don't care much, but maybe keeping them means we have less to convert / less opportunity to introduce bugs in the cleanup? I wouldn't just want to redirect `Info` to `Infoln` because then you always need to remember that they work differently than the stdlib's `fmt` functions...

**Comment by fabxc** [comment]
Yea, true. Adding in that repo.
